[package]
name = "config-catalog-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
lambda_http = "1.0.2"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
