[workspace]
resolver = "3"
members = ["config-catalog-api", "config-catalog-events"]

[workspace.dependencies]
tokio = { version = "1", features = ["macros"] }
serde = "1.0.228"
serde_json = "1.0"

[profile.release-strip]
inherits = "release"
strip = "symbols"
