events:
  - namespace: home-gateway
    keys:
      - config.yaml
    notify:
      type: HTTP
      method: POST
      audience: home-gateway
      urls:
        - https://home.anurag.sh/v1/config/refresh
