apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.17.2/cluster-operator.yml
  - https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/observability/prometheus/monitors/rabbitmq-servicemonitor.yml
  - https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/observability/prometheus/monitors/rabbitmq-cluster-operator-podmonitor.yml
  - cluster.yaml
  - tcproute.yaml

patches:
  - path: namespace.yaml
    target:
      kind: Namespace
      name: rabbitmq-system
