[package]
name = "config-catalog-jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
hmac = "0.12.1"
sha2 = "0.10.9"
serde = "1.0.228"
thiserror = "2.0.17"
chrono = "0.4.42"
